version: '3'
services:
  ia:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src
      - ./hiiamsid/:/hiiamsid
    ports:
      - "8900:8000"
    env_file:
      - .env
